### ISSUE TITLE
Where To Put Join Message Code

### ISSUE THREAD

**Issue by Edwardthedog2** [EndKingdom/SAM-BETA#5]
I know what code to use for the join message, but I'm not sure where to put it. Should it go in the Web.php file, so it can interact with the website connecting code, or in its own file? Or should it go in the SAM.php file?

**Comment by matthew4444** [comment]
Hey

**Comment by matthew4444** [comment]
im thinking it should go in the web.php file

**Comment by Edwardthedog2** [comment]
Hmm. I just tried that, but the join messages still don't show. @HittmanA Can you take a look at this please, and try to work it.

**Comment by matthew4444** [comment]
Then try making its own file

**Comment by matthew4444** [comment]
And i started the enderauth for you ,the team can finish the rest,with me,and you

**Comment by Edwardthedog2** [comment]
Okay.

**Comment by matthew4444** [comment]
Anytime

**Comment by matthew4444** [comment]
lol its 4 30 pm est

**Comment by HittmanA** [comment]
Hey guys. Sorry I haven't replied I have been on a flight most of the day. Let me take a look.

**Comment by matthew4444** [comment]
Ok

**Comment by HittmanA** [comment]
Ok the issue is simple. In my code I have this:
    `if ($registered = FALSE)`
and I also have this:
    `if ($registered = TRUE)`
These check if the player is registered or not so it knows which message to send. You **MUST** set
    `$registered` 
To either TRUE or FALSE otherwise it doesn't know which message to display.

**Comment by matthew4444** [comment]
Thx,im talking with antoher member of this github members list

**Comment by HittmanA** [comment]
Ok

**Comment by HittmanA** [comment]
I set it up as a boolean to make it easy to use.

**Comment by matthew4444** [comment]
WERRE TALKING IN THE THEENDERCREEPER0 PLUGINS UNDER ISSUES SEVTION ILL SEE U THERE

**Comment by HittmanA** [comment]
What?

**Comment by matthew4444** [comment]
Were talking here
https://github.com/EndKingdom/Some-of-TheEnderCreeper0s-Plugins-AKA-Matthew4444s-Plugins-/issues/1

**Comment by matthew4444** [comment]
Im talking at https://github.com/EndKingdom/Some-of-TheEnderCreeper0s-Plugins-AKA-Matthew4444s-Plugins-/issues/1
while im talking to u
